# Copyright 2023 Kubespider
# SPDX-License-Identifier: Apache-2.0

name: Release Chrome Extension
on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  Release-Extension:
    name: Release Kubespider Chrome Extension
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Zip
        run: zip -r chrome-extension.zip chrome-extension
        shell: bash

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{github.event.release.tag_name}} chrome-extension.zip
        shell: bash
